Trainable Paras: 9988097
TRAIN FROM SCRATCH
0.0
  0%|                                                                    | 0/100 [00:03<?, ?it/s]
Traceback (most recent call last):                                      | 0/3625 [00:00<?, ?it/s]
  File "main.py", line 127, in <module>
    run_train(args)
  File "main.py", line 73, in run_train
    controller.train(dataset_train=train_dataset,  dataset_val=val_dataset,
  File "/home/nmduy/HADA/chau/HADA-LAVIS/Controller.py", line 457, in train
    loss_tr_dict = self.train_epoch(dataloader_train, idx_epoch, writer)
  File "/home/nmduy/HADA/chau/HADA-LAVIS/Controller.py", line 338, in train_epoch
    wandb.log(all_loss.item())
  File "/home/jarvis/anaconda3/envs/chau/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jarvis/anaconda3/envs/chau/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 342, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/jarvis/anaconda3/envs/chau/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 332, in wrapper
    return func(self, *args, **kwargs)
  File "/home/jarvis/anaconda3/envs/chau/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1748, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/jarvis/anaconda3/envs/chau/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1524, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary